### ISSUE TITLE
学长，这个能用吗

### ISSUE THREAD

**Issue by zhwdzh** [Summerki/CSUAutoHealthPunch#2]
前一段时间打卡界面更新了，之前用的python脚本挂了，那个学长好像没空修

**Comment by Summerki** [comment]
你好，这个仓库的打卡脚本现在不能正常使用，这个仓库是很久之前仿照别人python程序改写的，打卡页面现在更新了一些东西，所以不能正常使用。
首先建议你clone下来其他人最新的相关源码进行学习，其次学会抓包看看每次打卡向服务器提交了什么信息，这样写出一个相关的打卡脚本就不难了。
后面我还用js写了一版新的，配合github action使用效果挺不错的，不过放在了私有仓库里面。
上面给你一些思路了，希望你能自己实现一个~

**Comment by zhwdzh** [comment]
Thanks
